"""Copy this file to create a Playwright non-regression test.

Only update the configuration section and the code inside ``test.step`` blocks.
The browser, Zephyr reporting, screenshots, error logs, and trace are managed by
``master.py``.
"""

from playwright.sync_api import expect

from master import RegressionTest, configure_logging


# =============================================================================
# TEST CONFIGURATION - UPDATE THESE VALUES AFTER COPYING THE FILE
# =============================================================================

ISSUE_KEY = "ZTEST-00"
TEST_NAME = "Replace with the Zephyr test name"
BASE_URL = "https://replace-with-the-page-to-test"


def run_test() -> bool:
    """Execute the scenario and return True only when every step is successful."""

    test = RegressionTest(issue_key=ISSUE_KEY, test_name=TEST_NAME)

    with test:
        page = test.page
        assert page is not None  # The browser is ready after entering RegressionTest.

        # Step numbers must match the step order configured in Zephyr.
        with test.step(1, "Open the page under test"):
            page.goto(BASE_URL, wait_until="domcontentloaded")
            expect(page.locator("body")).to_be_visible()

            # Paste the relevant Playwright Codegen actions here.
            # Keep the existing page; do not paste Codegen's browser setup/cleanup.

        with test.step(2, "Replace with the second Zephyr step"):
            # Paste the actions generated by Codegen, then add an explicit
            # assertion with expect(...) that proves the expected result.
            raise NotImplementedError("Replace this line with the second test step")

        # Add further steps by copying the block above and incrementing the number.
        # Failures are recorded independently, so a failed step does not prevent
        # the following step from running.

    return test.success


if __name__ == "__main__":
    configure_logging()
    raise SystemExit(0 if run_test() else 1)
